### ISSUE TITLE
BarCanvas tooltips fail on 0.80.0

### ISSUE THREAD

**Issue by elliothomerwilkinson** [plouc/nivo#2216] opened 2023-01-11 16:44 UTC
**Describe/explain the bug**
Default tooltips no longer display on Canvas Bar charts and an error is emitted to the console

**To Reproduce**
1. Go to the nivo rocks website Canvas Bar demo https://nivo.rocks/bar/canvas/
2. Open the dev tools console
3. Hover your mouse over the bar chart
4. Observe no tooltip is shown
5. Observe an error is emitted to the console `t.getBBox is not a function`

**Expected behavior**
Tooltip should display in a similar fashion to the SVG Bar demo

**Screenshots**
<img width="1622" alt="image" src="https://user-images.githubusercontent.com/90405129/211864765-a45f3424-a6fb-428a-a8d6-1bc389620f6b.png">

**Additional context**
Only started occurring on version 0.80.0

**Comment by ansgarsteinkamp** [comment] 2023-02-20 17:48
Same problem here

**Comment by plouc** [comment] 2023-02-26 03:21
This is a duplicate of https://github.com/plouc/nivo/issues/2162

**Closed by plouc** 2023-02-26 03:21 UTC
