### ISSUE TITLE
Warning: Support for defaultProps will be removed from function components

### ISSUE THREAD

**Issue by donfour** [plouc/nivo#2415] opened 2023-08-17 18:44 UTC
**Describe/explain the bug**
Getting the following error when using Nivo with Next.js 13 inside `app` router:
```
app-index.js:31 Warning: Jr: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

It doesn't affect the chart rendering though. It's just a bit annoying to see a long error in the console. Other libraries are also seeing a similar issue:
- https://github.com/recharts/recharts/issues/3615
- https://github.com/chakra-ui/chakra-ui/issues/7057

Wondering if Nivo has a plan to move from `defaultProps` to JS default parameters? It seems like quite a large refactor. Happy to contribute if needed. Thanks!

**To Reproduce**
Codesandbox: https://codesandbox.io/p/sandbox/frosty-tom-fgddxp

1. Go to the codesandbox
2. Open the preview in a new tab
3. Open dev tool console

**Expected behavior**
Rendering a chart should throw no error.

**Comment by RobertAron** [comment] 2023-08-30 14:26
I'm running into this issue as well. The warning is quite long also, which makes it difficult to parse other logs that appear in the inspector.

I understand this could be a large refactor... If anyone has suggestions for a hack to suppress warnings about this issue temporarily I would really appreciate it ❤️

**Comment by bernatfortet** [comment] 2023-09-18 22:38
Any updates on this? 
Has anyone found a way to hide the warnings?

**Comment by andre19980** [comment] 2023-10-20 18:53
I tried to do the refactor (based in the similar issue that @donfour linked to the description) but the deploy has failed and I guess I don't have access to vercel to see the logs :(
It's my first contribution, so I'm not really sure if I did all correctly

**Comment by Sinakhx** [comment] 2024-01-13 07:52
still looking forward for the fix

**Comment by dreampulse** [comment] 2024-01-29 09:31
I fixed that by patching the `console.log`, since the warning is polluting the developer experience.
(And for me, the issue is just occurring in external libraries)

```js
if (process.env.NODE_ENV !== "production") {
  // eslint-disable-next-line no-console
  const originalWarn = console.error;
  // eslint-disable-next-line no-console
  console.error = (...args) => {
    if (
      args[0].includes(
        "Support for defaultProps will be removed from function components in a future major release.",
      )
    ) {
      return;
    }
    originalWarn(...args);
  };
}
```

**Comment by ClydSpyd** [comment] 2024-02-09 18:00
Hello!

Any update on this issue?

**Comment by andre19980** [comment] 2024-02-14 18:48
@ClydSpyd it's waiting for a release! @plouc Any plans to release a new version soon? Is there something I can help?

**Comment by plouc** [comment] 2024-03-04 00:51
Sorry, I just didn't have the time to release, I'll try to find some time in the upcoming weeks.

**Comment by emiliodacosta** [comment] 2024-03-29 05:35
> I fixed that by patching the `console.log`, since the warning is polluting the developer experience. (And for me, the issue is just occurring in external libraries)
> 
> ```js
> if (process.env.NODE_ENV !== "production") {
>   // eslint-disable-next-line no-console
>   const originalWarn = console.error;
>   // eslint-disable-next-line no-console
>   console.error = (...args) => {
>     if (
>       args[0].includes(
>         "Support for defaultProps will be removed from function components in a future major release.",
>       )
>     ) {
>       return;
>     }
>     originalWarn(...args);
>   };
> }
> ```

@dreampulse where did you put this code for it to work?

**Comment by rahul8864** [comment] 2024-04-23 03:52
![image](https://github.com/plouc/nivo/assets/74202040/121c7fc5-3e2f-4cd0-b259-6799d165d9d3)

I noticed the warning message only appears locally and not in production. (ReCharts)

**Comment by edu-amr** [comment] 2024-05-06 17:04
Something similar is happening at https://github.com/recharts/recharts/issues/3615

**Comment by hassansw** [comment] 2024-05-19 16:31
`const originalConsoleError = console.error;

// Override console.error to filter out logs containing the specified string
console.error = (message, ...args) => {
    // Check if the message contains the specified string
    if (typeof message === 'string' && message.includes('defaultProps will be removed')) {
        // Ignore this log
        return;
    }

    // If the log doesn't contain the specified string, call the original console.error
    originalConsoleError.apply(console, [message, ...args]);
};`

Done

**Comment by plouc** [comment] 2024-05-21 00:05
This issue has been fixed in the latest version.

**Closed by plouc** 2024-05-21 00:05 UTC

**Comment by lokichaulagain** [comment] 2024-10-26 03:57
> ```
> if (process.env.NODE_ENV !== "production") {
>   // eslint-disable-next-line no-console
>   const originalWarn = console.error;
>   // eslint-disable-next-line no-console
>   console.error = (...args) => {
>     if (
>       args[0].includes(
>         "Support for defaultProps will be removed from function components in a future major release.",
>       )
>     ) {
>       return;
>     }
>     originalWarn(...args);
>   };
> }
> ```
> 
> Can someone guide me where to put above code? I am using NextJs



In your Nextjs Page where are are using the react-beautiful-dnd library.

```
"use client";
import dynamic from "next/dynamic";
const DraggableList = dynamic(() => import("./(components)/DraggableList"), { ssr: false });

export default function Page() {
  //  Hide warning message from react-beautiful-dnd library
  const originalWarn = console.error;
  console.error = (...args) => {
    const warningMessage = args[0];
    if (warningMessage.includes("Support for defaultProps will be removed from function components in a future major release.") || warningMessage.includes("Support for defaultProps will be removed from memo components in a future major release.")) {
      return;
    }
    originalWarn(...args);
  };

  return (
    <div>
      <h1 className="text-xl font-bold mb-4">Draggable List</h1>
      <DraggableList />
    </div>
  );
}
```
