### ISSUE TITLE
Custom Canvas Layer lineGenerator requires {x, y}[][]?

### ISSUE THREAD

**Issue by IVIyg0t** [plouc/nivo#1766] opened 2021-09-07 15:11 UTC
Hi all, I'm trying to write a custom canvas layer that will set the width of a specific line on a plot to double the width of the rest of the lines.

So far, it seems to make sense, but I'm not understanding what the `lineGenerator` is expecting as input.

Here is my customLine function:

```
  const customLine = ({
    series,
    ctx,
    lineWidth,
    lineGenerator,
  }: CustomCanvasLayerProps) => {
    lineGenerator.context(ctx);
    series.map((s) => {
      ctx.strokeStyle = s.color as string;
      ctx.lineWidth = (s.id as string).includes("PDP")
        ? (lineWidth as number) * 2
        : (lineWidth as number);
      ctx.beginPath();
      lineGenerator(s.data.map(d => d.position))
      ctx.stroke();
    });
  };
```

The `lineGenerator(s.data.map(d => d.position))` line is complaining with the following error:

```
No overload matches this call.
  Overload 1 of 2, '(data: { x: number; y: number; }[][]): string | null', gave the following error.
    Argument of type '{ x: number; y: number; }[]' is not assignable to parameter of type '{ x: number; y: number; }[][]'.
      Type '{ x: number; y: number; }' is missing the following properties from type '{ x: number; y: number; }[]': length, pop, push, concat, and 28 more.
  Overload 2 of 2, '(data: { x: number; y: number; }[][]): void', gave the following error.
    Argument of type '{ x: number; y: number; }[]' is not assignable to parameter of type '{ x: number; y: number; }[][]'.ts(2769)
```

Why does `lineGenerator` expect an array of arrays?  From what I can tell, the piece of code I was using as a [guide](https://github.com/plouc/nivo/blob/ce7c755b23cfc55ead9bac9920a55ef6e764bd99/packages/line/src/LineCanvas.js#L190-L199) doesn't seem to run into this issue.

Any ideas?

Thank you!

**Comment by wyze** [comment] 2021-09-08 11:26
Duplicate of #1604.

**Comment by wyze** [comment] 2021-09-08 11:27
The type is being produced incorrectly.

**Closed by wyze** 2021-09-08 11:26 UTC
