### ISSUE TITLE
Can't install with React 17

### ISSUE THREAD

**Issue by rap2hpoutre** [plouc/nivo#1450] opened 2021-03-15 08:51 UTC
I just tried to install it and get this message:

```
npm i @nivo/core

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   peer react@"^16.9.0 || ^17" from @next/react-dev-overlay@10.0.8
npm ERR!   node_modules/@next/react-dev-overlay
npm ERR!     @next/react-dev-overlay@"10.0.8" from next@10.0.8
npm ERR!     node_modules/next
npm ERR!       next@"10.0.8" from the root project
npm ERR!   peer react@"^16.6.0 || ^17" from next@10.0.8
npm ERR!   node_modules/next
npm ERR!     next@"10.0.8" from the root project
npm ERR!   6 more (react-dom, styled-jsx, swr, use-subscription, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from recompose@0.30.0
npm ERR! node_modules/@nivo/core/node_modules/recompose
npm ERR!   recompose@"^0.30.0" from @nivo/core@0.67.0
npm ERR!   node_modules/@nivo/core
npm ERR!     @nivo/core@"*" from the root project
npm ERR!     1 more (@nivo/tooltip)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/raph/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raph/.npm/_logs/2021-03-15T08_47_12_930Z-debug.log
```

It seems it's due to recompose that is abandoned: https://github.com/acdlite/recompose#a-note-from-the-author-acdlite-oct-25-2018

**Comment by maldan** [comment] 2021-04-18 23:22
Same

**Comment by marcelojrfarias** [comment] 2021-04-20 13:05
Same

**Comment by wyze** [comment] 2021-04-23 19:44
We are tracking the progress of removing recompose in #884. Going to close this since it shares the same root cause.

**Closed by wyze** 2021-04-23 19:44 UTC
