### ISSUE TITLE
Fix canvas scatterplot website example

### ISSUE THREAD

**Issue by amigolargo** [plouc/nivo#1081] opened 2020-08-03 14:35 UTC
1. Visit https://nivo.rocks/scatterplot/canvas/
2. Note errors as per attached image

**Expected behavior**
A functional example of the canvas scatterplot

<img width="504" alt="Screenshot 2020-08-03 at 16 32 14" src="https://user-images.githubusercontent.com/356134/89194199-588b4b80-d5a7-11ea-80e8-4b51e78c1134.png">

**Comment by wyze** [comment] 2020-08-03 20:45
Duplicate of #1069.

**Closed by wyze** 2020-08-03 20:45 UTC
