### ISSUE TITLE
🚩Custom Legend causes infinite re-render! 🚩

### ISSUE THREAD

**Issue by ZombieChowder11** [plouc/nivo#2591] opened 2024-05-16 20:49 UTC
**Describe/explain the bug**
Using `forwardLegendData` with `ResponsivePie` causes the page re-render infinitely!

**To Reproduce**
Sandbox reproducing the issue: https://codesandbox.io/p/sandbox/focused-euler-sq9s3p

1. Go to the sandbox
2. Open the console and watch the page re-render.

**Expected behavior**
The expected behavior is for the page **NOT** to re-render infinitely whenever someone creates a custom legend. 

My code is based on the official storybook documentation: https://github.com/plouc/nivo/blob/master/storybook/stories/pie/Pie.stories.tsx#L308

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 124.0.6367.207

**Comment by plouc** [comment] 2024-05-16 21:37
Duplicate of https://github.com/plouc/nivo/issues/2569.

**Closed by plouc** 2024-05-16 21:37 UTC
