### ISSUE TITLE
Allowing composition via render-props?

### ISSUE THREAD

**Issue by ncknuna** [plouc/nivo#358] opened 2018-11-27 02:48 UTC
First of all, thanks for an awesome library!

I'd like to add extra annotations to the svg wrapping the Line chart (some from d3-annotations like https://github.com/plouc/nivo/issues/125, and some custom ones), but I don't see an easy way to do that since Line doesn't accept any props that will render inside the SVGWrapper. 

This blog post outlines a way (https://medium.com/@gmonne/create-a-brush-component-using-nivo-dataviz-library-68074f3721ba), but it'd be much easier if there was a way to pass a function as a prop (maybe `children`, since that seems unused?) that would take the props available in the SVGWrapper as input and get rendered inside the SVGWrapper. 

If this is already possible somehow some other way, I'm definitely open to alternatives. Also totally understand if this would open up a bit more flexibility than you want to support right now.

**Comment by plouc** [comment] 2018-11-27 02:57
Hi @ncknuna,

I've started to introduce a `layers` property which allows to pass extra layers and also to change the order of elements. I didn't used children because of sorting, annotations should appear on top in your case, but let's say you want to add an area behind a scatterplot, it won't work.

For now, it's supported on [`Bar`](https://github.com/plouc/nivo/blob/master/packages/bar/src/Bar.js) and [`ScatterPlot`](https://github.com/plouc/nivo/blob/master/packages/scatterplot/src/ScatterPlot.js) components. You can find a working example of it [here](https://codesandbox.io/s/kkqmx1rw17) using the `ScatterPlot` component.

It's not supported yet for `Line`, but if you're willing to contribute, do not hesitate :)

**Comment by plouc** [comment] 2018-11-27 02:59
However this issue is a duplicate of https://github.com/plouc/nivo/issues/139, feel free to add your comment there.

**Closed by plouc** 2018-11-27 02:59 UTC
