### ISSUE TITLE
TimeRange emptyColor

### ISSUE THREAD

**Issue by anton-johansson** [plouc/nivo#1661] opened 2021-07-05 14:43 UTC
**Describe/explain the bug**

According to the documentation, the `TimeRange` (and `ResponsiveTimeRange`) should have the `emptyColor` property, just like the `Calendar` component. You can see it [here](https://nivo.rocks/time-range/):
> An array of colors to be used in conjunction with domain to compute days' color. It applies to days having a value defined, otherwise, emptyColor will be used.

**To Reproduce**
https://codesandbox.io/s/frosty-swartz-07f8z?file=/src/App.js

**Expected behavior**
I expect the `emptyColor` property to exist and have an effect. In my case, the time range will feel very empty if I don't have those "empty" boxes. :(

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 90.0.4430.93

**Additional context**

**Comment by yozibak** [comment] 2021-08-12 09:50
Hi, I also want this feature to be added. 
Though my current workaround here is to generate Array of objects which value is 0, 
and set the first item of color array to be `emptyColor`. 

<img width="657" alt="Screen Shot 2021-08-12 at 18 47 58" src="https://user-images.githubusercontent.com/58211188/129176440-a73dc8f4-60dd-4ce9-a03b-1b0af8d511f9.png">

But the problem is if the data value range is rather large, smaller value items also set to be `emptyColor`.
Or can I set each item with specific color?

**Comment by vgeary96** [comment] 2021-08-16 16:42
We wanted to use the TimeRange component as well but this is stopping us. Looking at the code I think the best way to go about this would be to add support for `from`, `to`, and `emptyColor` props and support holes in the data set like the Calendar component.

@wyze have those features already been planned out? If not I'd be willing to give it a go.

**Comment by wyze** [comment] 2021-08-16 16:59
Not planned out, a PR would be great.

**Comment by vgeary96** [comment] 2021-08-18 17:11
@wyze let me know what you think :) #1722

**Comment by wyze** [comment] 2021-08-23 11:36
Closed via #1722.

**Closed by wyze** 2021-08-23 11:36 UTC
Labels: :calendar: calendar, :new: feature request

**Comment by 321ckatz123** [comment] 2021-10-04 16:44
@wyze this does not appear to have ben pushed to npm. Can you please push this PR?

**Comment by plouc** [comment] 2021-10-09 23:21
@321ckatz123, I just published `0.74.0`, which includes this.
