### ISSUE TITLE
Modifying legend text / label

### ISSUE THREAD

**Issue by oscargws** [plouc/nivo#791] opened 2019-12-11 04:41 UTC
I need to be able to update the legend text in order to add some formatting features for readability. Is this currently possible to do in a bar / pie chart?

Something like:

 ```
               legends={[
                    {
                        dataFrom: 'indexes',
                        anchor: 'top-right',
                        direction: 'column',
                        justify: false,
                        translateX: 450,
                        translateY: 0,
                        itemsSpacing: 12,
                        itemWidth: 380,
                        itemHeight: 20,
                        itemDirection: 'left-to-right',
                        itemOpacity: 1,
                        symbolSize: 16,
                        legendFormat: d => d.value + d.id, // attempting to format here
                        symbolShape: ({ x, y, size, fill, borderWidth, borderColor }: LegendProps) => (
                            <LegendSymbol x={x} y={y} size={size} fill={fill} borderWidth={borderWidth} borderColor={borderColor} />
                        )
                    }
                ]}
```

However `legendFormat` seems to have no effect.

**Comment by wyze** [comment] 2019-12-11 12:40
You would set the `data` property on the object in the legend. There you set a `label` property and that is what is used.

It is typed as the following shape, but I guess `label` needs to be added there.

```
        data?: Array<{
            id: string | number
            value: number
            color?: string
            fill?: string
        }>
```

**Comment by arikaa** [comment] 2019-12-13 17:37
I'm using a function like this to format / update using the label property instead of the legendFormat.
`label={d => d.total+ d.value}`

**Comment by nerdess** [comment] 2020-02-15 13:02
i've got the same issue, i'd like to customize what is displayed in the legend of a pie chart.

@wyze can you please post a more detailed example as i got trouble following your suggestion. e.g. i am not sure what you mean with "set the data property on the object in the legend"....

this is what i got so far (only the relevant stuff)...

**current behavior**: the legend displays the id.
**expected behavior**: the legend should display what is inside "label".

`var data = [
    {
        id: 1,
        label: "freddy",
        value: 53,
    },
    {
        id: 2,
        label: "mary",
        value: 14
    },
    {
        id: 3,
        label: "lisa",
        value: 8
    },
    {
        id: 4,
        label: "john",
        value: 13
    },
    {
        id: 5,
        label: "bob",
        value: 13
    }
];`

`                legends={[
                    {
                        anchor: 'right',
                        direction: 'column',
                        translateY: 0,
                        itemWidth: 100,
                        itemHeight: 18,
                        itemTextColor: '#999',
                        symbolSize: 18,
                        symbolShape: 'circle'
                    }
                ]}`

**Comment by wyze** [comment] 2020-02-17 15:43
Here is another way to do it, where you render the legend manually: https://codesandbox.io/s/nivopie-typescript-4qvmh

**Comment by dkim-thomas** [comment] 2020-05-20 01:57
Hey @wyze, 

Thanks for providing a codesandbox rendering the legend manually (your response to @nerdess). How would you map the colors properly if you were using Nivo's color scheme? For example my reponsive pie chart using colors = { scheme: 'category10' }, but I don't seem to have access to the colors within my the component  <BoxLegendSvg/>

**Comment by wyze** [comment] 2020-05-20 02:21
@dkim-thomas You can do something like this, which uses the same data from the CodeSandbox:

```ts
import { categoricalColorSchemes } from '@nivo/colors'

const { category10 } = categoricalColorSchemes

const data = [
  {
    id: 'css',
    label: 'css (custom)',
    value: 410
  },
  {
    id: 'sass',
    label: 'sass',
    value: 175
  },
  {
    id: 'javascript',
    label: 'javascript',
    value: 128
  }
].map((item, index) => ({ ...item, color: category10[index] }))
```

**Comment by dkim-thomas** [comment] 2020-05-20 02:34
Thank you @wyze 

Appreciate the rapid response! Is there a way to use the legend prop on the <ResponsivePie/> to achieve a custom legend label? I saw other PR that allowed for this with bargraphs and such but as I attempted to use the same strategy for ReponsivePie it failed.

**Example:**
`<ResponsivePie
        animate={true}
        colors={colors}
        data={data}
        legends={[
          {
            data: data.map((item, index) => {
              return {
                color: ['#000', '#111', '#222'][index],
                id: item.id,
                label: item.label
              };
            }),
            anchor: 'right',
            direction: 'column',
            // translateY: 63,
            translateX: 140,
            itemWidth: 80,
            itemHeight: 20,
            // itemDirection: 'left-to-right',
            symbolSize: 14,
            symbolShape: 'circle'
          }
        ]}
/>`

**Comment by wyze** [comment] 2020-05-20 02:53
Yes, we need to get that merged in so it can be in the next release, because the pie chart will currently only use the `id` for the label.

**Comment by wyze** [comment] 2020-05-22 02:01
I merged a fix, so this will be out in the next release.

**Closed by wyze** 2020-05-22 02:01 UTC

**Comment by anirudh-0** [comment] 2020-11-10 18:52
Hi @wyze , I think the data property on a legend is now non-functional as it get replaced by `getLegendData` in "Bar.js". Is there an existing alternative to achieve this currently?

**Comment by wyze** [comment] 2020-11-16 15:45
@anirudh-0 I can't find where bar supported a custom label. Currently you would need to render this as a custom layer to replace the legend layer.

**Comment by matchatype** [comment] 2021-01-06 10:11
> Here is another way to do it, where you render the legend manually: https://codesandbox.io/s/nivopie-typescript-4qvmh

Could you please provide an example for radar charts too? I'm unable to customize legends.

**Comment by mboutin-qohash** [comment] 2021-03-30 13:13
This is not legend formatting but setting a label on a data. It's really not the same and just make another point that this lib is not mature for good chart solution

**Comment by dubzzz** [comment] 2022-01-21 18:07
@wyze I know you closed the issue a while ago but I'm wondering why Line charts are not offering an option like `legendLabel` as Bar charts do 🤔 

In the code of `packages/line/src/hooks.js`, we can see the following:
```js
    const { legendData, series } = useMemo(() => {
        const dataWithColor = data.map(line => ({
            id: line.id,
            label: line.id,       // <---- why can't we pass something to pass a label instead? or map to a label
            color: getColor(line),
        }))
        const series = dataWithColor
            .map(datum => ({
                ...rawSeries.find(serie => serie.id === datum.id),
                color: datum.color,
            }))
            .filter(item => Boolean(item.id))
        const legendData = dataWithColor
            .map(item => ({ ...item, hidden: !series.find(serie => serie.id === item.id) }))
            .reverse()

        return { legendData, series }
    }, [data, rawSeries, getColor])
```

While in bar we have:
```ts
    const legendsWithData: [BarLegendProps, LegendData[]][] = useMemo(
        () =>
            legends.map(legend => {
                const data = getLegendData({
                    bars: legend.dataFrom === 'keys' ? legendData : bars,
                    direction: legend.direction,
                    from: legend.dataFrom,
                    groupMode,
                    layout,
                    legendLabel,         // <---- this can be used to map ids to proper labels
                    reverse,
                })

                return [legend, data]
            }),
        [legends, legendData, bars, groupMode, layout, legendLabel, reverse]
    )
```

Any reason not to offer something similar for Line?


<details>
<summary>Here is an example with Bar charts:</summary>

```ts
import { Bar } from "@nivo/bar";

export default function App() {
  return (
    <Bar
      width={500}
      height={500}
      indexBy="reference"
      keys={["id-001", "id-002"]}
      data={[
        { reference: "ref-001", "id-001": 5, "id-002": 8 },
        { reference: "ref-002", "id-001": 7, "id-002": 2 }
      ]}
      margin={{ top: 50, right: 130, bottom: 50, left: 60 }}
      legendLabel={(d) => (d.id === "id-001" ? "France" : "England")}
      legends={[
        {
          dataFrom: "keys",
          anchor: "bottom-right",
          direction: "column",
          justify: false,
          translateX: 120,
          translateY: 0,
          itemsSpacing: 2,
          itemWidth: 100,
          itemHeight: 20,
          itemDirection: "left-to-right",
          itemOpacity: 0.85,
          symbolSize: 20
        }
      ]}
      axisBottom={{
        format: (v) => (v === "ref-001" ? "Banana" : "Watermelon")
      }}
    />
  );
}
```
</details>

Link: https://codesandbox.io/s/angry-ganguly-k07so?file=/src/App.js

**Comment by Binb1** [comment] 2022-02-25 15:58
@wyze to add to @dubzzz point, it looks like using the pattern you suggest won't work on canvas mode.
```
legends: [
            {
              dataFrom: 'keys',
              data: items.map((item, index) => ({ //Does not work if the chart is a canvas
                id: item.id,
                label: item.label
                color: item.color,
              }),
             ...
```
This will only render the ids in canvas mode.
