### ISSUE TITLE
Wrap text for long labels into multiple lines for Radar charts

### ISSUE THREAD

**Issue by archatas** [plouc/nivo#614] opened 2019-07-03 01:51 UTC
I love the nivo radar widget, but I find it disadvantageous when the labels are too long and don't fit into one line. The labels themselves are user-generated, so I don't control their length (for now).

It would be good if it was allowed to wrap text automatically, or at least to programmatically define breaks for the new lines.

An alternative would be to show the beginning of the label from left to right, cut it where it doesn't fit with an ellipsis, and show a tooltip on hover with the full text.

**Comment by plouc** [comment] 2019-07-03 12:20
I'm going to close this as it's a duplicate of https://github.com/plouc/nivo/issues/353.

**Closed by plouc** 2019-07-03 12:20 UTC
