### ISSUE TITLE
Line mesh tooltip is broken when it contains coincident points

### ISSUE THREAD

**Issue by Keenic** [plouc/nivo#546] opened 2019-05-14 14:26 UTC
Hello, I have 2 data sets with 11 items in data and there is no mesh tooltip displayed. Checked the `handleMouseMove` function in the `voronei Mesh` and the `index` is -1. 
Code to reproduce:
[https://codesandbox.io/s/pplwy182v0](https://codesandbox.io/s/pplwy182v0)
[https://codesandbox.io/s/3lz4m3lj1](https://codesandbox.io/s/3lz4m3lj1) - working example with 10 items in the data

**Comment by plouc** [comment] 2019-05-14 14:42
It's really weird, if I remove the last point from the first serie, it works, I'm not sure it comes from nivo or the underlying `d3-delaunay` module…

**Comment by plouc** [comment] 2019-05-14 14:44
I'll try to reproduce this using the same values but just with `d3-delaunay` to see what happens

**Comment by plouc** [comment] 2019-05-14 15:11
It seems to be a bug with `d3-delaunay` (https://github.com/d3/d3-delaunay/issues/55), if you change the value of the first point to avoid having a coincident point, it works.

**Comment by plouc** [comment] 2019-05-15 05:12
I'm closing this in favor of https://github.com/plouc/nivo/issues/545

**Closed by plouc** 2019-05-15 05:12 UTC
Labels: :beetle: bug, :chart_with_upwards_trend: line, :no_entry_sign: blocked
