### ISSUE TITLE
Customize grid spacing

### ISSUE THREAD

**Issue by pvjones** [plouc/nivo#148] opened 2018-02-10 20:53 UTC
Probably a neophyte question here. Is there a way to customize the grid spacing / interval on Bar or ResponsiveBar?

**Comment by plouc** [comment] 2018-05-18 19:53
There's an existing MR on this https://github.com/plouc/nivo/pull/170

**Comment by plouc** [comment] 2018-05-30 01:52
duplicate of https://github.com/plouc/nivo/issues/73

**Closed by plouc** 2018-05-30 01:52 UTC
