### ISSUE TITLE
TreeMapHtml error on isInteractive

### ISSUE THREAD

**Issue by SomeMoosery** [plouc/nivo#528] opened 2019-05-01 18:48 UTC
I am currently using React, attempting to create a Treemap and have been running into issues all of a sudden. I have previously been able to create treemaps fine by using the following: 

```
<ResponsiveTreeMapHtml
        root={<...>}
        identity="name"
        value={<...>}
        innerPadding={3}
        outerPadding={8}
        margin={{
          top: 37,
          right: 10,
          bottom: 10,
          left: 10,
        }}
        label="name"
        labelSkipSize={12}
        labelTextColor="#111"
        colors={colors}
        colorBy="name"
        borderColor="inherit:darker(0.3)"
        borderWidth={2}
        animate
        motionStiffness={60}
        motionDamping={11}
      />
``` 
(I've left certain features as <...> here for privacy's sake.

I know this is not an issue with my code, because up until we create the ResponsiveTreeMapHtml, everything is working fine, and no null or undefined values are being passed in. Now, when trying to plot a treemap I see the error: 

![treemap_error](https://user-images.githubusercontent.com/15767602/57035329-5bb2c180-6c17-11e9-81b2-7964f844554c.png)

I'm not sure why this has occurred all of a sudden, and I have tried adding the isInteractive parameter when creating the component. Although, this component has worked for weeks previously just fine, and seem to have just recently broken. 

Any help would be much appreciated.

**Comment by plouc** [comment] 2019-05-01 21:11
Hi @SomeMoosery,

As asked in the issue template, can you please reproduce this on codesandbox?

**Comment by plouc** [comment] 2019-05-08 09:55
@SomeMoosery any update? Unless you can provide an example of your issue, I'm gonna close this.
Thank you

**Comment by plouc** [comment] 2019-05-14 15:52
I'm closing this due to lack of reply, feel free to comment if you can provide a running example.

**Closed by plouc** 2019-05-14 15:52 UTC
Labels: :warning: awaiting feedback, :warning: invalid
