### ISSUE TITLE
Clicking on axisTop, axisRight is opening up a blank page.

### ISSUE THREAD

**Issue by vcdas123** [plouc/nivo#2487] opened 2023-12-06 07:55 UTC
1. When I am clicking on this option (axisTop, axisRight), a blank page is opening:
![Screenshot 2023-12-06 132056](https://github.com/plouc/nivo/assets/54539941/edae37ba-9daa-4f0b-8c5b-472cf13547a5)

2. Blank Page:
![Screenshot 2023-12-06 132150](https://github.com/plouc/nivo/assets/54539941/0d99e6c5-2145-40a4-b93a-5b652894912f)

**Comment by plouc** [comment] 2023-12-06 07:57
Duplicate of https://github.com/plouc/nivo/issues/2486

**Closed by plouc** 2023-12-06 07:57 UTC
