### ISSUE TITLE
SVG Axis Label Text Wrap

### ISSUE THREAD

**Issue by rpearce** [plouc/nivo#353] opened 2018-11-21 19:14 UTC
Hi, thanks for this sweet project! I know SVG `<text>` elements don't quite wrap yet, and I was wondering if I've missed a way to get axis label text to wrap that currently exists in this project? I've come across https://github.com/d3plus/d3plus-text, but I'm unsure of ways to interop between nivo & d3. There is also the hacky `<tspan>` element which could be deployed at some level, but that feels like I'm barking up the wrong tree.

Has this problem already been solved? If not, is it planned on being solved, or is help required?

<img width="989" alt="image" src="https://user-images.githubusercontent.com/592876/48863397-13080880-ee2e-11e8-9775-124214e01e5e.png">

**Comment by plouc** [comment] 2018-11-21 19:40
Hi @rpearce,

You'll have to use `tspan` for now, the problem with SVG text wrap support in nivo, is the various chart implementations: SVG/Canvas/HTML.

Also nivo provides an HTTP rendering API and all the existing solutions relies on the DOM to get text size and stuff, making those unusable for SSR :(

The first step to make this less annoying should be to support line breaks at least.

**Comment by rpearce** [comment] 2018-11-21 19:45
Alright, I'll see what I can cook up. Thanks for getting back so quickly

**Comment by plouc** [comment] 2018-11-21 19:58
Maybe you can try to use the lib you mentioned using a custom `renderTick` function, however it seems that the lib adds several deps which can increase the size of your bundle, and are somehow useless in a React context such as `d3-selection`.

**Comment by rpearce** [comment] 2018-11-21 19:59
On the SSR-side, would pre-rendering on the server with [GoogleChrome/puppeteer](https://github.com/GoogleChrome/puppeteer) allow for that sort of analysis? Sounds more like a paid service at that point :)

I'll try a custom `renderTick` but perhaps without that lib

**Comment by plouc** [comment] 2018-11-21 20:02
yes you could use puppeteer, but that's a whole different kind of setup :)
for example [this](https://nivo-api.herokuapp.com/r/4641f47a-c0d0-4aeb-aa7c-a3ba96262a28) is generated using `react-dom/server`.

**Comment by rpearce** [comment] 2018-11-21 20:03
Gotcha. That is very cool

**Comment by plouc** [comment] 2018-11-21 20:05
The repository is available here => https://github.com/plouc/nivo-api, but I'm currently moving it to the main repo.

**Comment by rpearce** [comment] 2018-11-25 03:09
Update: here's what I'm currently going with...
```js
axisBottom={{
  tickSize: 0,
  tickPadding: 25,
  tickRotation: 0,
  renderTick: ({
    opacity,
    textAnchor,
    textBaseline,
    textX,
    textY,
    theme,
    value,
    x,
    y
  }) => {
    return (
      <g
        transform={`translate(${x},${y})`}
        style={{ opacity }}
      >
        <text
          alignmentBaseline={textBaseline}
          style={theme.axis.ticks.text}
          textAnchor={textAnchor}
          transform={`translate(${textX},${textY})`}
        >
          {getTspanGroups(value)}
        </text>
      </g>
    )
  }
}}
```
where `getTspanGroups` is an Array of `<tspan>` elements that are no longer than 15 characters (not dynamic ... but passable).

Best I can do for now!

**Comment by plouc** [comment] 2019-03-24 07:14
@rpearce, `foreignObject` is not processable by simple SVG viewers, that's why I avoid using it.

**Comment by plouc** [comment] 2019-03-24 07:36
also, it won't work for canvas implementations :/

**Comment by elyfuentes27** [comment] 2019-06-13 18:23
is there a way to wrap text in axisLeft?  I tried to write a function and add it to the tspan, but it doesn't work . 

```
    wrapType(str) {
        if (str.length > 16) {
            // if string is longer than 16 characters
            var p = 16;
            while (p > 0) {
                // loop through the string and check each char
                if ((str.charAt(p) === " " || str.charAt(p) === "-")) {
                    // if a dash or space is found, wrap the string
                    var left = (str.charAt(p) === "-") ? str.substring(0, p + 1) : str.substring(0, p);
                    var right = str.substring(p + 1);
                    return left + "\n" + this.wrapType(right); // return the wrapped string
                }
                p--;
            }
        }
        return str; // return the original string
    }
```
 
```
 axisLeft={{
            tickSize: 10,
            tickPadding: 5,
            tickRotation: 1,
            legend: '', 
            legendPosition: 'middle',
            legendOffset: -40,
              renderTick: ({
                opacity,
                textAnchor,
                textBaseline,
                textX,
                textY,
                theme,
                value,
                x,
                y
            }) => {
                return (
                <g
                transform={`translate(${x},${y})`}
                >
                    <text
                    alignmentBaseline={textBaseline}
                    textAnchor={textAnchor}
                    transform={`translate(${textX},${textY})`}
                    >
                    {this.wrapType(value)}
                    </text>
                </g>
                )
            }
        }}
```

![image](https://user-images.githubusercontent.com/44783309/59457540-74dd8f00-8dcd-11e9-97f4-8c85182bf4f9.png)

**Comment by plouc** [comment] 2019-06-29 02:57
@elyfuentes27, I don't see where you used a `tspan`

**Comment by elyfuentes27** [comment] 2019-07-08 21:24
@plouc Yes, I tried that but didn't work so I removed it from the code. Any suggestion of what should I do in this situation? Thank you

**Comment by plouc** [comment] 2019-07-12 05:48
@elyfuentes27, can you please reproduce what you tried on codesandbox? thanks

**Comment by elyfuentes27** [comment] 2019-07-12 22:18
@plouc  Thanks for taking some time from your busy schedule! Here is a link to an example of what I tried to do. 
https://codesandbox.io/embed/dazzling-khorana-83r62
Not Sure what are my options. 
Maybe
1. Could we have something like Readmore or less? 
2. On Hover only shows full label Text, and on Axis we Truncate Text. 

Thanks!

**Comment by elyfuentes27** [comment] 2019-07-23 20:28
@plouc Hi! Just wondering if you were able to check the link I sent you. Thank you!

**Comment by marcx28** [comment] 2019-07-25 12:59
hi

**Comment by elyfuentes27** [comment] 2019-07-25 19:35
Hi! 
Just FYI I did the following to deal with this : 
1.  Used : `https://www.npmjs.com/package/truncate-html` to truncate Axis Label 
2. Added the complete string in the tooltip : 

`        tooltip={({ indexValue, value, color }) => (
            <strong>
               {indexValue}: <tspan style={{color: color}}>{value}</tspan>
            </strong>
        )}`

Thanks!

**Comment by CallumHemsley** [comment] 2019-09-26 14:56
@elyfuentes27 can you show us a codesandbox of what you changed to make it work? I don't quite understand..

**Comment by elyfuentes27** [comment] 2019-09-26 16:15
@CallumHemsley   -> This is just an example:
[https://codesandbox.io/embed/react-bar-chart-using-nivo-83r62?fontsize=14](url). 
Hope this helps.

**Comment by CallumHemsley** [comment] 2019-09-27 07:39
@elyfuentes27 Hey thanks for the fast response. Looking at that example, the axis values on the left don't seem to be wrapped? Maybe I misunderstood what you were doing?

**Comment by CallumHemsley** [comment] 2019-09-27 09:45
@elyfuentes27 Thank you.

**Comment by rpearce** [comment] 2019-09-27 13:21
> @rpearce where are you getting the `theme` attribute from? Mine is undefined when trying to use your code

At the time of writing, `theme` is pulled off of an object sent by nivo in the callback for `renderTick`. Separately, `theme` was something passed in to nivo components then, as well (an object for defining your defaults).

Unfortunately, I am not using nivo any more and am not up to date on the changes that have happened in the past year.

**Comment by tylercrosse** [comment] 2019-12-11 22:40
Here's what worked for me.

```js
axisLeft: {
        tickSize: 8,
        tickPadding: 4,
        renderTick: HorizontalTick,
      },
```

```
/**
 * Returns a tick element that wraps text for the given number of lines and adds an ellipsis if the text can't fit. This can be passed to the renderTick method.
 */
const HorizontalTick = ({ textAnchor, textBaseline, value, x, y }) => {
  const MAX_LINE_LENGTH = 16;
  const MAX_LINES = 2;
  const LENGTH_OF_ELLIPSIS = 3;
  const TRIM_LENGTH = MAX_LINE_LENGTH * MAX_LINES - LENGTH_OF_ELLIPSIS;
  const trimWordsOverLength = new RegExp(`^(.{${TRIM_LENGTH}}[^\\w]*).*`);
  const groupWordsByLength = new RegExp(
    `([^\\s].{0,${MAX_LINE_LENGTH}}(?=[\\s\\W]|$))`,
    'gm',
  );
  const splitValues = value
    .replace(trimWordsOverLength, '$1...')
    .match(groupWordsByLength)
    .slice(0, 2)
    .map((val, i) => (
      <tspan
        key={val}
        dy={12 * i}
        x={-10}
        style={{ fontFamily: 'sans-serif', fontSize: '11px' }}
      >
        {val}
      </tspan>
    ));
  return (
    <g transform={`translate(${x},${y})`}>
      <text alignmentBaseline={textBaseline} textAnchor={textAnchor}>
        {splitValues}
      </text>
    </g>
  );
};
```js

**Comment by sibelius** [comment] 2019-12-16 22:20
use `@vx/text`

  ```jsx
import React from 'react';
import { Text } from '@vx/text';

const RadarLabel = ({ id, anchor }) => {
  return (
    <g transform={`translate(${anchor === 'end' ? -60 : anchor === 'middle' ? -30 : 0}, -20)`}>
      <Text
        width={200}
        fontSize='10px'
        verticalAnchor={anchor}
      >
        {id}
      </Text>
    </g>
  );
};

export default RadarLabel;
```

**Comment by plouc** [comment] 2020-01-15 11:10
This won't be supported as it's specific to SVG, please have a look at the suggested approaches if you want to implement this.

**Closed by plouc** 2020-01-15 11:10 UTC
Labels: :triangular_ruler: axes

**Comment by Lekha30** [comment] 2020-04-08 02:47
@plouc, 
will this renderTick work with tickRotation? I see the renderTick working fine but the tickRotation is not happening whenever I use renderTick. Is there a way to get it to working?

**Comment by ymenase** [comment] 2020-04-22 20:41
I have my axis bottom formatted like this:
                        format: '%m/%d/%Y %H:%M %p',
I want the time to appear on a new line. Every way of trying to split on new line doesn't work or gives me an extra space. I think I am going to have to wrap the to go to another line like some of the responses above. However, the responses above seem very elaborate. Is there a more elegant way of doing this within nivo chart? Thanks.

**Comment by dkim-thomas** [comment] 2020-05-20 20:48
> @rpearce, `foreignObject` is not processable by simple SVG viewers, that's why I avoid using it.

@plouc so does this mean foreignObject will not render? I am on a project that does not need to support various browsers (we are using puppeteer to generate PDFs). I attempted to use foreignObject within the pie chart radial label to achieve word wrapping. 

I see the foreignObject within the DOM but it is hidden.

thanks!

**Comment by EddyJens** [comment] 2020-05-21 12:43
@tylercrosse do you have a sandbox example of this code? I tryed in my own code, but didn't worked ...

**Comment by ThinkSalat** [comment] 2021-01-14 18:33
Hi, I'm trying to get my left axis labels to wrap on a horizontal bar chart, anyone have a solution to this yet?

**Comment by lesagi** [comment] 2021-02-25 20:36
> Hi, I'm trying to get my left axis labels to wrap on a horizontal bar chart, anyone has a solution to this yet?

Hi, having the same issue, the above implementation doesn't work for me.

**Comment by JannVazTor** [comment] 2021-05-24 17:38
> Rotation
 
Adding `rotate` to transform did the trick for me, 
` transform={translate(${textX},${textY}) rotate(${-40})}`

**Comment by JannVazTor** [comment] 2021-05-24 17:38
> @plouc,
> will this renderTick work with tickRotation? I see the renderTick working fine but the tickRotation is not happening whenever I use renderTick. Is there a way to get it to working?

Adding `rotate` to transform did the trick for me, 
` transform={translate(${textX},${textY}) rotate(${-40})}`

**Comment by dlaub3** [comment] 2021-09-08 16:33
> @CallumHemsley -> This is just an example:
> https://codesandbox.io/embed/react-bar-chart-using-nivo-83r62
> Hope this helps.

I'm fixing this link since it doesn't work correctly.

**Comment by nappalm** [comment] 2022-12-26 23:25
> use `@vx/text`
> 
> ```js
> import React from 'react';
> import { Text } from '@vx/text';
> 
> const RadarLabel = ({ id, anchor }) => {
> return (
>   <g transform={`translate(${anchor === 'end' ? -60 : anchor === 'middle' ? -30 : 0}, -20)`}>
>     <Text
>       width={200}
>       fontSize='10px'
>       verticalAnchor={anchor}
>     >
>       {id}
>     </Text>
>   </g>
> );
> };
> 
> export default RadarLabel;
> ```

How to implement this in the radar chart?
