### ISSUE TITLE
React 18 and Canvas-Components

### ISSUE THREAD

**Issue by ansgarsteinkamp** [plouc/nivo#2249] opened 2023-02-22 17:57 UTC
Nivo 0.80.0 / React 18: Is there any hope for an update of Nivo to solve the problems with canvas-components? They are completely unusable using React 18 (=> Nivo 0.80.0).
#2162
#2166
#2216

**Comment by plouc** [comment] 2023-02-26 03:18
This is a duplicate of https://github.com/plouc/nivo/issues/2162 (as the canvas issue is not specific to React 18). It's been fixed but I had some issues releasing due to some other changes I didn't have the time to solve yet.

**Closed by plouc** 2023-02-26 03:18 UTC
