### ISSUE TITLE
Handling long legend text string

### ISSUE THREAD

**Issue by techhysahil** [plouc/nivo#616] opened 2019-07-03 12:05 UTC
First of all, I would like to Thanks everyone for their contribution to this library.  

I am having an issue displaying a large text string in legends. For explaining my problem I have created a [codesandbox](https://codesandbox.io/s/bar-graph-nivo-test-9p2wp). 

<img width="1386" alt="Screenshot 2019-07-03 at 5 33 00 PM" src="https://user-images.githubusercontent.com/7847056/60590060-a805b380-9db8-11e9-849b-c81bd8b86667.png">

As you can see, Text on X-axis is totally cluttered and unreadable. Any suggestion/solution would really be appreciated.

**Comment by plouc** [comment] 2019-07-03 12:18
svg doesn't support text wrap, you can override the labels by using the axis `renderTick` property and use a custom function using text wrap or ellipsis or you can rotate the labels and increase the bottom margin.

**Comment by plouc** [comment] 2019-07-03 12:20
I'm going to close this as it's a duplicate of https://github.com/plouc/nivo/issues/353, please have a look at it as some users suggested some approach to solve this.

**Closed by plouc** 2019-07-03 12:20 UTC

**Comment by techhysahil** [comment] 2019-07-03 15:53
Thanks @plouc,  other thread link you mentioned was quite helpful.

**Comment by marcx28** [comment] 2019-07-04 06:31
@techhysahil How did you do that in the end? I tried the code from #353 but it does not really work at all.

**Comment by lolz42** [comment] 2019-07-23 09:01
Guys, labels on x-axis could be overridden by `renderTick ` property but what to do if a label text is too long?

![legend-text](https://user-images.githubusercontent.com/31371916/61698078-c700c100-ad38-11e9-91a8-5d42f7750d1e.png)
