### ISSUE TITLE
Combined line and bar chart?

### ISSUE THREAD

**Issue by samb8s** [plouc/nivo#141] opened 2018-02-01 08:44 UTC
I'm struggling to see an example of having a shared y-axis as follows: a bar chart showing, say, profit per year, and then a line on the same chart to show cumulative profit.

Is this possible?

**Comment by plouc** [comment] 2018-02-01 08:46
It's a duplicate of https://github.com/plouc/nivo/issues/139

**Closed by plouc** 2018-02-01 08:46 UTC
