### ISSUE TITLE
Labels and Bar doesn't show up when the value is too small in grouped mode

### ISSUE THREAD

**Issue by HelloKashif** [plouc/nivo#509] opened 2019-04-05 04:51 UTC
Chart Type: Bar

CodeSandbox: https://codesandbox.io/embed/535j62oz64

Consider this data.
 {
                    key1: 9512.0976,
                    key2: 4000.0032,
                    key3: 3.4515000000000002,
                    key4: 107.1447,
                    key5: 4000.0032,
                    key6: 0,
                    key7: 0,
                    key8: 321.42960000000005,
                    time: "2019-04"
 }

When in groupMode=grouped mode using this data will not show key3 in label and actual bar because it's too small compared to other values. 

This seems like a bug. Any value if it's greater than 0 should be be visible no matter how small it is.

**Comment by plouc** [comment] 2019-04-05 05:25
Please consider reproducing this issue on a platform like codesandbox like asked in the issue template, thank you!

**Comment by s-kashif** [comment] 2019-04-05 06:50
Sorry, Added codesandbox link

**Comment by plouc** [comment] 2019-04-05 07:03
Thank you!

**Comment by claytongomes** [comment] 2019-04-11 00:22
The same issue here, not necessarily for zero, any small value in the grouped bar doesn't render. Should be interesting to render it and also use a minimum height, so we could still see them in the chart and use the tooltips.

**Comment by plouc** [comment] 2019-05-02 13:49
@claytongomes, minimum won't be supported, it misleading as it won't reflect the actual size of the corresponding value, if you want to show small values, maybe you should consider another strategy such as grouping all small values and adding another chart which focus on those.

**Comment by plouc** [comment] 2019-05-02 14:20
@s-kashif, only zero height bars are skipped, there's not much to do about this.
- https://github.com/plouc/nivo/blob/master/packages/bar/src/compute/stacked.js#L90
- https://github.com/plouc/nivo/blob/master/packages/bar/src/compute/stacked.js#L103

**Comment by plouc** [comment] 2019-05-02 14:32
I missed you were talking about grouped bars, and the height of the bar in your case is 0.1875px

**Comment by plouc** [comment] 2019-05-02 14:44
It's weird… using the same data, the bar is rendered locally
<img width="419" alt="Capture d’écran 2019-05-02 à 23 43 13" src="https://user-images.githubusercontent.com/501642/57083830-23ed6c00-6d34-11e9-805e-2d952f225bf3.png">

**Comment by cazroam** [comment] 2019-07-26 03:52
Is there a way to have the label show when mouse hovers over the column of the (invisible) small value? 
I can't see how to override the default behaviour.

**Comment by domidemps** [comment] 2019-10-17 15:27
As @cazroam, I'm wondering if there is a way to override the default behavior of the tooltip hovering, because I'm experiencing the same problem with "invisible" small values...
I would like a hovering on the whole column and not only on the corresponding bar.
If I find a way to do it, I'll let you know!

**Comment by 4-life** [comment] 2020-01-24 14:05
Any news?

**Comment by Stoffy92** [comment] 2020-03-25 23:19
@domidemps did you figure this out?

> As @cazroam, I'm wondering if there is a way to override the default behavior of the tooltip hovering, because I'm experiencing the same problem with "invisible" small values...
> I would like a hovering on the whole column and not only on the corresponding bar.
> If I find a way to do it, I'll let you know!

Did you figure this out?

**Comment by jurgisrudaks** [comment] 2020-04-07 19:56
I'm experiencing the same issue - i have data set where there is value of 1 - i display the data using the responsive bar component as stacked bar chart - at specific widths the bar with value 1 disappears - and then reappears when resized to different width.

![Kapture 2020-04-07 at 22 54 46](https://user-images.githubusercontent.com/4631864/78713362-d6558800-7922-11ea-9432-486883fedc3e.gif)

**Comment by teddybee** [comment] 2020-05-02 00:16
I have similar issue with Responsivebar. I have a kind of horizontal RaceBar(only one value per BarComponent). If a value smaller than  1/1000 of the largest value, the bar component simply doesn't show at all. Not even the ID. For example I have 9 items in this chart, but the 4th item's value is 10. I only see 3 barcomponents instead of 9.
![image](https://user-images.githubusercontent.com/11610010/80850156-cd529080-8c1a-11ea-86ca-8823be4f0bd4.png)

**Comment by JulienTimsch** [comment] 2020-05-15 12:02
Exactly same issue as @teddybee.
I could reduce the breaking point at which a smaller variable isn't displayed by removing styling options (`innerPadding`) but the problem still occurs if the difference between values is too large.

**Comment by JulienTimsch** [comment] 2020-09-24 14:17
Please any news?

**Comment by teddybee** [comment] 2020-11-07 00:27
The issue also effects the extra layers. 
For example I draw an avarage line on the bars, but the layer generathor method don't get as long array with bar elemnts than it should be. The less than 1 px tall/long bars simply evaporate. I had 120 items for data, and got 105 in the generator's bar array.

**Comment by wyze** [comment] 2020-11-07 01:40
We added the ability (0.64) to set the scale type for the value via `valueScale`, exactly like xScale/yScale from line or valueScale from swarmplot. You can see the modified sandbox from @HelloKashif's initial description here: https://codesandbox.io/s/sleepy-elion-i8oq4

> I had 120 items for data, and got 105 in the generator's bar array.

This should no longer be the case on the latest version, as we don't do any filtering of values anymore, they just do not render with our default BarItem component.

**Closed** 2020-11-07 01:40 UTC
Labels: :bar_chart: bar, bug

**Comment by teddybee** [comment] 2020-11-07 13:03
I can confirm, with 0.64 my isues have been gone. Thank you wyze. (I used 0.63.1 when I wrote that yesterday)

**Comment by vikrant-gembrill** [comment] 2021-06-17 12:01
@wyze for me the bar chart is still not showing the lables if the value is small
![image](https://user-images.githubusercontent.com/75779649/122392759-cd822c80-cf91-11eb-886e-6dad64824801.png)

**Comment by maulep1** [comment] 2024-08-13 12:54
Hello @teddybee @wyze same issue here we still cannot display very small values. Could you please help?
