### ISSUE TITLE
Suggestion - Line graph with horizontal scrolling capabilities

### ISSUE THREAD

**Issue by gioragutt** [plouc/nivo#108] opened 2017-12-09 17:28 UTC
I've not yet seen this component around,

A graph where I can have lines (spanning from x1 -> x2, with several points with different heights),
And also have a horizontal scrolling capability, for when I want to show state over time and so on.

**Comment by plouc** [comment] 2017-12-09 18:25
Something like [this](https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172)?

**Comment by demartsc** [comment] 2017-12-09 18:28
Brush and zoom capability would be a great add, they were also suggested in #31 and #32

**Comment by plouc** [comment] 2017-12-09 18:34
A lot of work for those features :) I'm willing to add it, but probably not in a near future.
If someone is interested in working on this, do not hesitate to throw a PR, I'll be more than happy!

**Comment by plouc** [comment] 2017-12-09 18:35
@gioragutt, if what you meant was brushing, I'll close this one and flag it as duplicate in favor of https://github.com/plouc/nivo/issues/32.

**Comment by gioragutt** [comment] 2017-12-09 19:03
@plouc It seems like that is what I meant, as long as this equally reflects on line graphs as well.

Just for some context, my use case is to show chains of events, sort of message chains from one process from another, and show the chains in a graph.

P.S: Saw your profile picture, immediately remembered seeing it [here](https://medium.freecodecamp.org/a-look-back-at-the-state-of-javascript-in-2017-a5b7f562e977). Now I realize I saw your repo from this post :laughing:

**Comment by plouc** [comment] 2017-12-15 07:36
duplicate of https://github.com/plouc/nivo/issues/32

**Closed by plouc** 2017-12-15 07:36 UTC
