### ISSUE TITLE
Scatterplot Custom Tooltip

### ISSUE THREAD

**Issue by Aphsai** [plouc/nivo#228] opened 2018-06-18 20:21 UTC
I was wondering if some support could be added for a custom tooltip to the scatterplot like the other components.

**Comment by plouc** [comment] 2018-07-12 20:04
It's a duplicate of https://github.com/plouc/nivo/issues/192, custom tooltips are planned for all components, but contributions are welcome ;)

**Closed by plouc** 2018-07-12 20:04 UTC
