### ISSUE TITLE
@nivo/Sankey enableLinkGradient not supported in Safari Desktop, and all browsers on mobile

### ISSUE THREAD

**Issue by shellyscheng** [plouc/nivo#2637] opened 2024-08-15 22:31 UTC
**Thanks for using nivo**

Before creating an issue...

**Are you asking a question?**

Please don't file GitHub issues to ask questions.
Try to use the discord channel first: https://discord.gg/n7Ft74f.

**Describe/explain the bug**

Hi, I'm trying to use `enableLinkGraidient = {true}` for my sankey chart. However, it was shown as grey in Safri. It works fine in Chrome, Firefox, etc.

Could someone look into the issue and fix it? Thanks a lot!

**To Reproduce**
Please **include a test case that demonstrates the issue you're reporting on a platform like codesandbox**, I already have several existing examples on codesandbox, you can fork one of them
depending on the component you're working on: https://codesandbox.io/u/plouc/sandboxes.
This is very critical to maintainers in order to help us see the issue you're seeing.

**Expected behavior**

**Screenshots**

Screenshots are from Storybook

enableLinkGraident={true} in Safari Desktop:
![Screenshot 2024-08-15 at 3 27 09 PM](https://github.com/user-attachments/assets/2745a7ac-09a6-4510-ad33-f6db4466f087)

enableLinkGraident={false} working correctly: 
![Screenshot 2024-08-15 at 3 27 19 PM](https://github.com/user-attachments/assets/c4273e80-d388-4b92-b99a-85b8e8e99519)

I also tested on Chrome, Safari app on my iPhone, and the link is also gray when `enableLinkGradient={true}`
![IMG_2400](https://github.com/user-attachments/assets/c7930bcf-6fc4-40ff-a39a-056581307f1b)

**Desktop (please complete the following information):**
 - OS: 14.5 
 - Browser: Safari
 - Version: 17.5

** Mobile:**
 - Device: iPhone 14 Pro
 - OS: 17.5.1
 - Browser Chrome, Safari

**Comment by plouc** [comment] 2024-08-16 00:11
Closing this issue as it's a duplicate of https://github.com/plouc/nivo/issues/2045.

**Closed by plouc** 2024-08-16 00:11 UTC
