### ISSUE TITLE
TypeError: Cannot read property 'animate' of undefined

### ISSUE THREAD

**Issue by OlegAnn** [plouc/nivo#603] opened 2019-06-22 21:24 UTC
Used library in React.js 
![Снимок экрана от 2019-06-23 00-21-08](https://user-images.githubusercontent.com/33581180/59969035-1e025300-954d-11e9-9f96-c2be0dcab8b5.png)

if render , getting this error

animate = _useMotionConfig.animate

**Comment by plouc** [comment] 2019-06-23 02:04
Hi @OlegAnn,
Can you please reproduce this issue on codesandbox, it'll be difficult to help otherwise.
Thank you.

**Comment by tomyates** [comment] 2019-06-28 09:00
@OlegAnn I had this error when using ResponsiveScatterPlot with the example data from https://nivo.rocks/scatterplot/

I ended up using the slightly older release of @nivo/scatterplot

`yarn add @nivo/scatterplot@v0.58.0`

**Comment by jberube** [comment] 2019-06-29 00:46
I have the same error after upgrading from `0.51.0` to `0.58.0`, using `@nivo/bar`.

**Comment by plouc** [comment] 2019-06-29 01:58
Which React version are you using? Did you tried latest `0.59.0` version of the component?

**Comment by plouc** [comment] 2019-06-29 01:59
It's really difficult to help on issues without any context or way to reproduce, that's the purpose of the issue template.

**Comment by vnponce** [comment] 2019-06-30 20:35
I fixed it deleting `node_modules` and `npm install`. 
I had the same error when I just updated from 0.56.2 to 0.59.1 `@nivo/line`

**Comment by tomyates** [comment] 2019-06-30 20:37
> It's really difficult to help on issues without any context or way to reproduce, that's the purpose of the issue template.

Sorry Plouc - will do next time. Thanks for your help.

**Comment by jberube** [comment] 2019-07-01 03:26
> Which React version are you using? Did you tried latest `0.59.1` version of the component?

I use e `react@16.8.6`, and using `@nivo/bar@0.59.0` I had another issue, cause by the `theme` not being available from callbacks, same issue as https://github.com/plouc/nivo/issues/579

I could try with `0.59.1`, does it contain a fix for this issue or #579 ?

**Comment by stahlmanDesign** [comment] 2019-07-02 16:30
I have the same error `TypeError: _useMotionConfig is undefined` in `0.59.0` and `0.59.1`.

Looks like a problem with `nivo-axes.esm.js`. Will attempt to reproduce in code sandbox. 

`0.58.0` does not have the error

Using react `16.8.6` and create-react-app.
Deleting /node_modules and reinstalling does not fix it for me.


<img width="1041" alt="Capture d’écran, le 2019-07-02 à 12 09 24" src="https://user-images.githubusercontent.com/972804/60528769-37c93600-9cc3-11e9-9053-b58994653ac0.png">
<img width="1059" alt="Capture d’écran, le 2019-07-02 à 12 09 41" src="https://user-images.githubusercontent.com/972804/60528775-3b5cbd00-9cc3-11e9-982a-496956adf513.png">

**Comment by stahlmanDesign** [comment] 2019-07-02 16:58
I hate to say it but I reinstalled `0.59.1` and I no longer have the bug. Maybe it did have something to do with deleting /node_modules

**Comment by di2pro** [comment] 2019-07-05 12:37
I faced the same issue, I use latest version of the libraries. I also was trying to reproduce it in the [codesandbox](https://codesandbox.io/embed/intelligent-cartwright-dv0vu) but it throws an error only if `enableSlices` is equal to `y` when in the application I use almost the same data except `enableSlices` is equal to `x`. So, if I'm turning it off (`enableSlices`), everything will be working fine

**Comment by plouc** [comment] 2019-07-09 07:05
Sorry but unless someone is able to reproduce this on codesandbox, I'm gonna close this issue, @di2pro, the error is different from the one originally mentioned here.

**Comment by di2pro** [comment] 2019-07-09 07:34
@plouc I understand, that's ok. I'll add an example once I reproduce it.

**Comment by plouc** [comment] 2019-07-11 22:44
I'm closing this, if someone is able to reproduce this please add a comment and I'll reopen.

**Closed by plouc** 2019-07-11 22:44 UTC
Labels: :warning: awaiting feedback, :warning: invalid

**Comment by barnapisti1994** [comment] 2019-08-08 08:44
I had similar issues a few days ago. I used d3.js in my application and I had an older version in my package.json. Upgrading to a new d3 version solved this problem with Nivo for me.

**Comment by HenriettaSoldOut** [comment] 2019-08-13 08:06
> I faced the same issue, I use latest version of the libraries. I also was trying to reproduce it in the [codesandbox](https://codesandbox.io/embed/intelligent-cartwright-dv0vu) but it throws an error only if `enableSlices` is equal to `y` when in the application I use almost the same data except `enableSlices` is equal to `x`. So, if I'm turning it off (`enableSlices`), everything will be working fine.
> 
> Update: Downgrading to `0.56.0` solved my problem, everything works good.
worked for me too thanks a lot!

**Comment by cruze17** [comment] 2019-12-04 21:44
I Had similar issues. resolved by downgrading nivo/radar lib and upgrading React-dom version.
nivo/radar: 0.56.2
React-dom: 16.8.0

**Comment by xavierrh** [comment] 2019-12-20 13:23
Hi,
I'm facing the same issue "TypeError: Cannot read property 'animate' of undefined" with @nivo/bar 0.61.0.
Moving to version 0.56.2 solved the issue.
I did not managed to reproduce it in a sandbox ye but I will try again.

**Comment by evantahler** [comment] 2019-12-23 22:30
I've had this issue too - It occurred when I had installed various @nivo types that were not of the same version.  Making them all the same version and re-installing fixed the issue

**Comment by ewarrenG** [comment] 2020-07-20 02:58
> I've had this issue too - It occurred when I had installed various @nivo types that were not of the same version. Making them all the same version and re-installing fixed the issue

+1

Struggled with this issue mysteriously popping up for a week or so. Syncing my @nivo types to the same version made this go away. I wish I had seen this answer soon.

**Comment by SnarkieDesign** [comment] 2020-07-23 03:13
Getting the same issue after updating all my nivo packages to `0.62.0`, deleting `node_modules` and reinstalling

**Comment by philj0st** [comment] 2020-07-24 14:57
i get the same issue when using `@nivo/scatterplot` haven't found a solution yet tho.

**Comment by NewbiZ** [comment] 2020-08-11 03:56
Have the same issue with `0.62.0`.
Easily reproducible:
- Use `create-react-app` for typescript
- `npm install @nivo/line`
- Copy paste a bare minimal `ResponsiveLine`.

**Comment by radiosterne** [comment] 2020-09-13 00:11
@plouc that is easily reproducible, as @NewbiZ pointed out — and it's already fixed in your current codebase. The issue lies in cyclic dependency between @nivo/core and @nivo/toolbar as of `0.62.0`, which forces npm or, indeed, yarn to include @nivo/core twice in resolution graph.

Now, as I can see, it's fixed via moving @nivo/tooltip to `peerDependencies` in @nivo/core's `package.json`. What plan have you got in mind on publishing this change to npm registry? Maybe, we can hotfix the issue at hand by publishing `0.62.1`, where changing dependency graph would be the only change?

**Comment by radiosterne** [comment] 2020-09-13 01:57
As per https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-plug-an-play.md, section `Virtual packages`:

> Plug'n'Play guarantees that each combination of package name / version will only be instantiated once by Node, except in one documented case: if a package has any number of peer dependencies, Node will instantiate them exactly once for each time it is found in the dependency tree - and this regardless of whether the packages are strictly identical or not.

So, given that @nivo/core has peerDependencies (rightly so) and given cyclic dependency between @nivo/core and @nivo/tooltip, if I'm understanding everything correctly, nivo won't ever work with yarn 2.

@plouc can you, please, explain the necessity of keeping `core` and `tooltip` in two separate NPM packages? I may be mistaken, but considering their intertwinement it seems like the easiest way to solve this problem is to include `tooltip` code in `core` code and deprecate `toolkit` package altogether.

**Comment by wyze** [comment] 2020-09-13 02:17
Yes, arcanis has brought it to our attention in #879. I've also removed the tooltip provider from `core` and moved it into `tooltip` so then each package will import it individually. This is in #1039 and will be part of TypeScript migration.

**Comment by radiosterne** [comment] 2020-09-13 15:02
@wyze that's great! Looking forward to TS migration as well!

However, while we are all waiting, I've cobbled together a version of nivo compatible with yarn 2 by removing tooltip package and cyclic dependency. It is available at NPM as `@blumenkraft/nivo-*` packages, if anyone is interested, and I intend to deprecate it in favor of mainline nivo as soon as yarn 2 support is merged and published.

Does it sit right with nivo development team?

**Comment by MadDeveloper** [comment] 2020-12-07 17:02
I was facing the same issue, when migrating from `0.59.2` to `0.66.0`.
Remove your `node_modules` folder, reinstall your dependencies (don't forget to install `@nivo/core` btw), upgrade all your chart packages (`@nivo/pie`, `@nivo/geo`, ...) to the same version of `@nivo/core`, and everything should work fine.

**Comment by plouc** [comment] 2021-05-26 10:56
@OscarBarrett, most internal nivo components rely on specific React contexts in order to work, here the context containing the animation config, you can fix this by wrapping this component with the `Container` component from `@nivo/core`, or have a look at [how it's injecting those contexts](https://github.com/plouc/nivo/blob/master/packages/core/src/components/Container.js) and just use the providers.

**Comment by ankush-003** [comment] 2024-05-05 04:12
I still get the same issue with nivo/line
![image](https://github.com/plouc/nivo/assets/94037471/8915a3b1-000e-4358-8bb8-653cc6b18b36)
    "@nivo/axes": "^0.86.0",
    "@nivo/line": "^0.86.0",

**Comment by plouc** [comment] 2024-05-05 04:32
I understand that some users deem something as easily reproducible by providing some text instructions, however it often takes quite some time to bootstrap the specific env in which the issue occurs. Also sometimes some crucial informations are omitted, like the node version, the nivo packages being used, their version...

That's why I ask for a codesandbox, it's now clearly stated in the issue template, and I would really appreciate if reporters conform to this template, the lib is provided for free, I think it's not unreasonable to ask users to put some effort into helping maintainers helping them :)

Now, regarding the issue at hand, this might be due to the cyclic import, `@nivo/tooltip` should probably be merged in `@nivo/core`.

**Comment by ankush-003** [comment] 2024-05-05 08:17
Thanks a lot for your response,
If the basic code given in the docs is not working properly, then i
dont think that you need sandbox and stuff to rectify that. The issue is
not even related to the versions.
Please do provide a better experience for the users next time as for me i
have found  a better and simpler solution by other library
Best Regards

**Comment by plouc** [comment] 2024-05-05 08:24
@ankush-003, I think you really missed the point, the code provided works, just look at the demo website, it seems it doesn't work in certain contexts.

**Comment by JSurquin** [comment] 2024-06-04 09:12
I had the same problem just now: I simply put the @nivo all in the same versions

![CleanShot 2024-06-04 at 11 11 17@2x](https://github.com/plouc/nivo/assets/33385043/bb2a6688-49b2-4d0b-8223-0b0c1376f6ae)

and before when it didn't work :

![CleanShot 2024-06-04 at 11 11 48@2x](https://github.com/plouc/nivo/assets/33385043/fb15c17a-a0a3-4ac1-b5de-f79af9727d5f)

I had the error : [TypeError: Cannot read property 'animate' of undefined](https://github.com/plouc/nivo/issues/603#top)

**Comment by jaderocks** [comment] 2024-12-19 09:30
SAME ISSUE
```
Unexpected Application Error!
Cannot read properties of undefined (reading 'animate')
TypeError: Cannot read properties of undefined (reading 'animate')
    at https://local.cloud.ebay.com:5173/node_modules/.vite/deps/@nivo_tree.js?v=0b5fb958:450:93
```

**Comment by barrelltech** [comment] 2025-05-13 08:41
I had the same issue. `@nivo/line` and `@nivo/theming` installed at `0.96.0`, everything else at `0.95.0`. Setting everything to the same version (`0.95.0`) resolved the issue

**Comment by bobinska-dev** [comment] 2025-07-04 20:07
Same! had 2 different version of @nivo packages installed which caused this issue > upgrading both to the same did the trick! Thanks @barrelltech !

**Comment by sagemihir** [comment] 2025-11-28 11:47
> I was facing the same issue, when migrating from `0.59.2` to `0.66.0`. Remove your `node_modules` folder, reinstall your dependencies (don't forget to install `@nivo/core` btw), upgrade all your chart packages (`@nivo/pie`, `@nivo/geo`, ...) to the same version of `@nivo/core`, and everything should work fine.

yes this helped, as my `@nivo/pie` was at `0.99.0 `and `@nivo/core` was `at 0.87.0` I was getting this error, but all sorted when matched those versions
