### ISSUE TITLE
Error t.useMemo using React 16.14.0

### ISSUE THREAD

**Issue by rociogarridofer** [plouc/nivo#2584] opened 2024-05-03 11:16 UTC
Using @nivo/line version 0.86.0 I get the following error:
![Captura desde 2024-05-03 13-11-58](https://github.com/plouc/nivo/assets/156098951/f9bb2d90-52ce-4b04-8cab-bbb8704b8eda)

According to the console bug it seems that the error is coming from this file:
https://github.com/plouc/nivo/blob/1ac1246c453587700aef86639d679ffdc11427da/packages/axes/src/compute.ts#L4

But I don't know if it's a bug in my version of react that doesn't interpret this file correctly or if it's a bug in the mentioned file.

Thank you very much!

**Comment by plouc** [comment] 2024-05-03 11:19
@rociogarridofer, could you please reproduce the issue in codesandbox for example? It's impossible to tell what the cause could be as is.

**Comment by rociogarridofer** [comment] 2024-05-03 12:27
@plouc Hello! the code is private to the company and I couldn't reproduce it in CodeSanbox sorry...

**Comment by plouc** [comment] 2024-05-03 12:33
@rociogarridofer, I'm going to close the issue then.

**Closed by plouc** 2024-05-03 12:33 UTC
Labels: :warning: awaiting feedback
