### ISSUE TITLE
Tooltip Doesn't Function like Dev on Next.js Build

### ISSUE THREAD

**Issue by hariria** [plouc/nivo#1397] opened 2021-01-23 22:58 UTC
**Describe/explain the bug**
When I use nivo scatterplot and pie charts and import them into my `next.js` project, the tooltips render correctly and follow my cursor as they should. However, when I **build** the project, ie. run

```
npm run build
```

and host the website, the tooltip doesn't follow my cursor anymore and the experience of using it is very different. Furthermore, I have inputs that change the `xScale` and `yScale` attributes of the graph, however, when those inputs change, the graph the x and y axis tickers start to overlap.

**To Reproduce**
Unfortunately this isn't something I can easily show with a codesandbox, however, if you build a next.js project with one of these graphs, this is seems to happen.

**Expected behavior**
Tooltip should follow cursor and there shouldn't be overlapping x and y axis tickers.

**Screenshots**

https://user-images.githubusercontent.com/31301117/105616390-5dc59800-5d8b-11eb-822c-48900f1194f8.mov

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Latest

**Comment by masch712** [comment] 2021-01-24 13:22
I'm seeing similar tooltip misbehavior from a bare create-react-app project with a ResponsiveLine component.  It works fine in dev, but the tooltips don't follow my cursor in the built, "production-optimized" js.
I tried Chrome, Firefox, and Safari; same misbehavior in all of them.

**Comment by wyze** [comment] 2021-01-25 16:18
Duplicate of #1290.

**Closed by wyze** 2021-01-25 16:18 UTC
