### ISSUE TITLE
v0.79.1 not present in repositories (npmjs  / yarnpkg)

### ISSUE THREAD

**Issue by fpavkovcek** [plouc/nivo#2051] opened 2022-06-17 10:01 UTC
Latest version (v0.79.1) of @nivo/core is not present in main npm repositories:
- https://www.npmjs.com/package/@nivo/core
- https://yarnpkg.com/package/@nivo/core

![image](https://user-images.githubusercontent.com/25825778/174275660-2ac07110-12e8-48c0-8ae8-869eb3328e86.png)

**Comment by tkonopka** [comment] 2022-06-17 11:05
(I'm not an author/maintainer of nivo, but hope this can help)

The version in the screenshot - @nivo/core 0.79.0 - is the latest and current version. Other packages that provide specific charts, e.g. @nivo/bar, have updated versions 0.79.1, but they all depend on core 0.79.0.

**Comment by plouc** [comment] 2022-06-17 21:39
Duplicate of https://github.com/plouc/nivo/issues/2002.

**Closed by plouc** 2022-06-17 21:39 UTC
