### ISSUE TITLE
How to format pie chart ?

### ISSUE THREAD

**Issue by Eric0201** [plouc/nivo#458] opened 2019-02-11 08:48 UTC
How to display pie chart with array one data? same picture
![screenshot from 2019-02-11 15-47-29](https://user-images.githubusercontent.com/38023513/52552923-80677c00-2e14-11e9-98dc-b18be87390c9.png)

**Comment by plouc** [comment] 2019-02-11 09:06
Duplicate of https://github.com/plouc/nivo/issues/434

**Closed by plouc** 2019-02-11 09:06 UTC

**Comment by Eric0201** [comment] 2019-02-11 09:43
no, I don't mean that. I mean like this http://ramblings.mcpher.com/Home/excelquirks/bigapps/bigquiz/dashtimer

**Comment by Eric0201** [comment] 2019-02-11 09:46
with 1 data it only accounts for 1 part of the pie chart, not all
