### ISSUE TITLE
ResponsiveLine: useMesh with less than 3 points

### ISSUE THREAD

**Issue by isidornygren** [plouc/nivo#572] opened 2019-05-29 16:08 UTC
Using a `ResponsiveLine` with the `useMesh` prop will cause the component to error if the data provided has less than 3 points.
```
Error: No Delaunay triangulation exists for this input.
```

**Comment by plouc** [comment] 2019-05-31 00:23
It's a duplicate of https://github.com/plouc/nivo/issues/545

**Closed by plouc** 2019-05-31 00:23 UTC
