### ISSUE TITLE
Website Crash opening line chart axis (left,right,bottom)

### ISSUE THREAD

**Issue by mawaisismail** [plouc/nivo#2486] opened 2023-12-05 08:21 UTC
**Describe/explain the bug**
when you open any axis on line chart it make website crash & blank screen

**To Reproduce**
1.Go to https://nivo.rocks/line/
2.scroll to Grid & Axis
3.expend axisLeft ,right,top,bottom 
Then it will crash website and show blank page
see error:
react-dom.production.min.js:127 Uncaught Error: no value defined for property: truncateTickAt ({
  "key": "truncateTickAt",
  "flavors": [
    "svg",
    "canvas",
    "api"
  ],
  "help": "Bottom prevent the tick from overlapping truncating it",
  "type": "number",
  "required": false,
  "control": {
    "type": "range",
    "min": 0,
    "max": 100
  },
  "name": "truncateTickAt",
  "group": "Grid & Axes"
}, {
  "path": [
    "axisBottom"
  ]
})

**Expected behavior**
website should not crash and open respective action against axis

**Screenshots**
![image](https://github.com/plouc/nivo/assets/100074373/176b979f-f0ac-417a-947f-8c9dc6e2149c)

![image](https://github.com/plouc/nivo/assets/100074373/3470a21a-715d-4d1a-9d6b-20bc8f50ab64)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [chrome]
 - Version 119.0.6045.199 (Official Build) (64-bit)

**Comment by plouc** [comment] 2023-12-06 07:57
Duplicate of https://github.com/plouc/nivo/issues/2484

**Closed by plouc** 2023-12-06 07:57 UTC
