### ISSUE TITLE
Server side rendering - "ResizeObserver is not defined" error

### ISSUE THREAD

**Issue by blaxk** [plouc/nivo#1895] opened 2022-01-18 01:31 UTC
**package.json**
```
{
   ...
   "@nivo/bar": "^0.79.1",
   "@nivo/core": "^0.79.0",
   "@nivo/line": "^0.79.1",
   "@nivo/pie": "^0.79.1",
   "next": "^12.0.8",
   "react": "^17.0.2",
   "react-dom": "^17.0.2",
}
```

**React.js + Next.js**

When I do server side rendering I get "ResizeObserver is not defined" error.

```
ReferenceError: ResizeObserver is not defined
    at /home/ec2-user/www/node_modules/@nivo/core/dist/nivo-core.cjs.js:1:12062
    at Ha (/home/ec2-user/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:26:317)
    at Object.useState (/home/ec2-user/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:301)
    at Object.exports.useState (/home/ec2-user/www/node_modules/react/cjs/react.production.min.js:23:281)
    at je (/home/ec2-user/www/node_modules/@nivo/core/dist/nivo-core.cjs.js:1:12041)
    at Ee (/home/ec2-user/www/node_modules/@nivo/core/dist/nivo-core.cjs.js:1:14782)
    at d (/home/ec2-user/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/home/ec2-user/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/home/ec2-user/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/home/ec2-user/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
```

There was no error in previous versions.

**Comment by plouc** [comment] 2022-01-18 02:25
Duplicate of https://github.com/plouc/nivo/issues/1889

**Closed by plouc** 2022-01-18 02:25 UTC
