### ISSUE TITLE
Update To React v18

### ISSUE THREAD

**Issue by miko-github** [plouc/nivo#2116] opened 2022-08-27 11:45 UTC
**Describe/explain the bug**
The React Version of `@nivo` was **16.\*** but should to update cause my app writed to new features in `React 18`, we cant move back to anyelse version.

1. Go to Terminal
2. Write `npm i @nivo/bar`
3. See error

**Screenshots**

![Screenshot from 2022-08-27 16-10-55](https://user-images.githubusercontent.com/64307152/187028625-c7f2fd23-9e92-4798-a183-1f4ce6abdb5a.png)

**Comment by plouc** [comment] 2022-08-29 05:48
Duplicate of https://github.com/plouc/nivo/issues/1964

**Closed by plouc** 2022-08-29 05:48 UTC
Labels: :warning: duplicate
