### ISSUE TITLE
How to customise line widths in @nivo/line chart?

### ISSUE THREAD

**Issue by abhijit-padhy** [plouc/nivo#300] opened 2018-09-27 07:20 UTC
I am using responsive line chart having 2 data sets. So I want one line of 18px width and other one default 2px width. 
How can I achieve this customisation?

**Comment by plouc** [comment] 2018-09-27 10:02
@abhijit-padhy, for now you cannot unfortunately, but that would be useful.
Also, sorry but I close this issue as it's a duplicate of https://github.com/plouc/nivo/issues/162.

**Closed by plouc** 2018-09-27 10:02 UTC
