### ISSUE TITLE
how to draw line graphs with different number of points per line

### ISSUE THREAD

**Issue by redi-lernera** [plouc/nivo#174] opened 2018-04-17 15:49 UTC
Folks, I am trying to draw multiple stacked lines, but they each have a different number of points.  I am getting "Error: Found inconsitent data for x, expecting all series to have same length but found: 3, 1".  So how do I do that without artificially generating additional points in order to fool your line chart into drawing itself?
thank you

**Comment by plouc** [comment] 2018-08-25 23:39
I close this as it's a duplicate of https://github.com/plouc/nivo/issues/80

**Closed by plouc** 2018-08-25 23:39 UTC
Labels: line
