### ISSUE TITLE
Pie Chart not animating

### ISSUE THREAD

**Issue by archieherbias** [plouc/nivo#118] opened 2017-12-16 04:47 UTC
I'm doing a pie chart with animation set to true but it seems it is not animating. Also in your documentation here http://nivo.rocks/#/pie/ it is not animating when you roll the dice.

Is it currently worked on? Because the other graphs have working animation.

**Comment by plouc** [comment] 2018-05-18 20:10
Duplicate of https://github.com/plouc/nivo/issues/39

**Closed by plouc** 2018-05-18 20:10 UTC
