### ISSUE TITLE
Cannot read property 'showTooltipAt' of undefined

### ISSUE THREAD

**Issue by john-pc** [plouc/nivo#590] opened 2019-06-11 10:32 UTC
when enabling useMesh on @nive/line there is "Cannot read property 'showTooltipAt' of undefined" error

**To Reproduce**
Copy and paste the same code as the example in 
https://nivo.rocks/line/

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 75.0.3770.80

**Additional context**
- React Version 16.8.6

**Comment by plouc** [comment] 2019-06-11 11:59
@john-pc, can you please reproduce this on codesandbox? This is the code used on the website and it works, so I don't see how I could reproduce this :)

**Comment by plouc** [comment] 2019-06-27 08:51
I'm closing this as there's not enough information.

**Closed by plouc** 2019-06-27 08:51 UTC
Labels: :warning: awaiting feedback

**Comment by john-martinez-729** [comment] 2019-12-20 16:27
I am having this same problem on both the Canvas and SVG versions.

**Comment by nodox** [comment] 2019-12-24 17:44
Seeing the same issue. Have you stopped trying to fix it?

**Comment by plouc** [comment] 2019-12-25 17:16
@nodox, which issue? I was unable to reproduce and asked for an example on codesandbox, and had no feedback. Please make sure the various nivo packages versions are the same, it might cause some issue

**Comment by Ajaay** [comment] 2020-03-15 21:29
I'm having the exact same issue but can't reproduce on codesandbox for some reason...

All my nivo packages are on the same version as well. Very strange..

**Comment by wilblack** [comment] 2020-09-20 17:55
I have the same issue. It occurred when upgrading from nivo/core@0.61.0, nivo/line@0.61.1 to nivo/core@0.62.0, nivo/line@0.62.0

**Comment by mferrario** [comment] 2020-10-28 14:36
I encountered the same problem. Checkout issue #800 

> Found the solution! Apparently because I have multiple charts with different versions, I had to normalize the versions (I changed them all in package.json to 0.60.0) and reran yarn. That seemed to fix the problem!

Changing all chart versions to 0.63.0 worked for me.
