### ISSUE TITLE
Tooltip ^0.79.0 not getting rendered with Heatmap and probably with other charts

### ISSUE THREAD

**Issue by SainsateSonik** [plouc/nivo#1893] opened 2022-01-17 14:14 UTC
**Steps Taken:**
Upgraded Heatmap from `0.75.0` to `0.79.1`.
Upgraded Tooltip from `0.75.0` to `0.79.0`.

The tooltip isn't visible anymore and the `tooltip` prop isn't rendering the custom tooltip if provided.

**Comment by plouc** [comment] 2022-01-17 14:20
Closing this as it seems to be a duplicate of https://github.com/plouc/nivo/issues/1823.

**Closed by plouc** 2022-01-17 14:20 UTC
