### ISSUE TITLE
"@nivo/bar": "^0.65.1" crashes when installed on its own.

### ISSUE THREAD

**Issue by RodrigoRoaRodriguez** [plouc/nivo#1294] opened 2020-11-17 14:47 UTC
**Describe/explain the bug**
"@nivo/bar": "^0.65.x" can no longer be installed on its own like  "@nivo/bar": "^0.64.x"  could.

**Steps to reproduce the behavior:**
Code sandbox: https://codesandbox.io/s/nivo-bar-0650-bug-k4zpn

1. Create a fresh react-app typescript project
2. Install @nivo/bar": "^0.65.x"
3. Import and use ResponsiveBar 

**Expected behavior** 
A bar chart is rendered.

**Actual behavior** 
 Missing dependency, @nivo/core crashes the project.

**Screenshots**
# @nivo/bar "^0.65.1"
![image](https://user-images.githubusercontent.com/6189778/99403861-3c5bb200-28eb-11eb-8585-9b3ff3cc1edb.png)

# @nivo/bar "^0.64.0"
![image](https://user-images.githubusercontent.com/6189778/99406271-ff44ef00-28ed-11eb-9553-a4012c68076e.png)

**Comment by wyze** [comment] 2020-11-17 15:38
Duplicate of #1286. You will need to install the peer dependency `@nivo/core` now. Website code has been updated to reflect this.

![image](https://user-images.githubusercontent.com/186971/99410919-a27b1180-28b8-11eb-9d2c-4ee2fcea2894.png)

**Closed by wyze** 2020-11-17 15:38 UTC
Labels: :warning: duplicate

**Comment by RodrigoRoaRodriguez** [comment] 2020-11-17 15:40
Thanks for the prompt reply 🙏

**Comment by wyze** [comment] 2020-11-17 15:53
No problem, sorry we through everyone off with this. Still trying to figure out the best way to document it.
