### ISSUE TITLE
TimeRange - Tooltips can be rendered off-screen

### ISSUE THREAD

**Issue by anton-johansson** [plouc/nivo#1765] opened 2021-09-06 15:26 UTC
**Describe/explain the bug**

When using tooltips for the `TimeRange` component, the tooltips can be placed off-screen if a day is close to the screen edge. See image below:
![image](https://user-images.githubusercontent.com/6347803/132236976-345c2a52-07ee-46b3-8aaa-258db57608eb.png)

**To Reproduce**

I tried creating a Code Sandbox with `@nivo/calendar`, but it kept complaining about:
> Could not find module in path: 'react/jsx-runtime' relative to '/node_modules/@nivo/tooltip/dist/nivo-tooltip.es.js'

**Expected behavior**

Not quite sure how we want it to work, but it would be great if the placement of the tooltip was adjusted to fit inside the screen boundaries. Not sure how to do this though.

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04
 - Browser: Chrome 92.0.4515.131

**Comment by plouc** [comment] 2021-09-06 15:30
I think this is a duplicate of https://github.com/plouc/nivo/issues/1765.

**Closed by plouc** 2021-09-06 15:30 UTC

**Comment by anton-johansson** [comment] 2021-09-06 16:21
@plouc, you linked to this issue. :smile:  Which one were you actually referring to?

**Comment by plouc** [comment] 2021-09-06 16:31
@anton-johansson, it's in the comment: https://github.com/plouc/nivo/issues/1765.

**Comment by anton-johansson** [comment] 2021-09-06 19:16
@plouc, #1765 is **this** issue. It can't really be a duplicate with itself can it? :smile:

**Comment by plouc** [comment] 2021-09-06 23:52
@anton-johansson, my bad 😅, indeed, it is https://github.com/plouc/nivo/issues/580.
