### ISSUE TITLE
Webpage crash

### ISSUE THREAD

**Issue by hdale94** [plouc/nivo#2376] opened 2023-06-26 08:31 UTC
In the Theming Guide (https://nivo.rocks/guides/theming/)

If you click on "tooltip.container", it will crash the webpage.

I am on MacBook using macOS Ventura with Chrome.

![Skjermbilde 2023-06-26 kl  10 29 26](https://github.com/plouc/nivo/assets/77438639/2fa4639a-26fc-40fb-8c72-4594eb8f24ca)

![Skjermbilde 2023-06-26 kl  10 30 42](https://github.com/plouc/nivo/assets/77438639/87de978a-352a-4b23-bb1c-d878ae999cbb)

**Comment by plouc** [comment] 2023-06-26 08:44
Duplicate of https://github.com/plouc/nivo/issues/2367

**Closed by plouc** 2023-06-26 08:44 UTC
